language: ruby
matrix:
  include:
    - rvm: 2.4.4
    - rvm: 2.3.1
      env: CUSTOM_RUBY_VERSION=2.3.1 ISOLATED=true
    - rvm: 2.2.4
      env: CUSTOM_RUBY_VERSION=2.2.4 ISOLATED=true

  fast_finish: true
  allow_failures:
    - rvm: 2.3.1
    - rvm: 2.2.4

sudo: false
bundler_args: --deployment --without development
cache:
  - bundler
  - directories:
    - node_modules
before_script:
  - ruby --version
  - cp config/database.ci.yml config/database.yml
  - cp .env.example .env
  - psql -c 'create database orientation_test;' -U postgres
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm --version
  - npm install -g yarn
  - yarn --version
  - yarn install
  - bundle exec rake db:migrate
script:
  - bundle exec rspec spec/
branches:
  only:
    - master
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    on_start: never
    rooms:
      secure: YBUcQpusC8+1Zoc4l1vcm3eH7IzvFcTayGfjHtLH0Ed9JtSVkwtDqJwQVn6mxS+syCJoYxO18RfHnHNYq32bs/YKPZN+HX/IFOB4lIxXSIACe9gZ497ASCs9eza8NhILZkRpUmEwBlsJVPRYMhyIglU+SO0I6hVBN4d2534FBu8=
addons:
  postgresql: "9.3"
  code_climate:
    repo_token: 75408d377a0b3c1ab512bf3fb634617bccf2a1065f8c513e352139427ec8e1fb
