language: ruby
matrix:
  include:
    - rvm: 2.6.3
    - rvm: 2.5.3
      env: CUSTOM_RUBY_VERSION=2.5.3 ISOLATED=true
    - rvm: 2.4.5
      env: CUSTOM_RUBY_VERSION=2.4.5 ISOLATED=true

  fast_finish: true
  allow_failures:
    - rvm: 2.5.3
    - rvm: 2.4.5
sudo: false
services:
  - redis-server
  - postgresql
bundler_args: --deployment --without development
cache:
  - bundler
  - directories:
    - node_modules
before_script:
  - ruby --version
  - cp config/database.ci.yml config/database.yml
  - cp .env.example .env
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm --version
  - npm install -g yarn
  - yarn --version
  - yarn install
  - bundle exec rake db:setup db:migrate
script:
  - bin/rspec spec/
branches:
  only:
    - master
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    on_start: never
    rooms:
      secure: YBUcQpusC8+1Zoc4l1vcm3eH7IzvFcTayGfjHtLH0Ed9JtSVkwtDqJwQVn6mxS+syCJoYxO18RfHnHNYq32bs/YKPZN+HX/IFOB4lIxXSIACe9gZ497ASCs9eza8NhILZkRpUmEwBlsJVPRYMhyIglU+SO0I6hVBN4d2534FBu8=
addons:
  postgresql: "10"
  code_climate:
    repo_token: 75408d377a0b3c1ab512bf3fb634617bccf2a1065f8c513e352139427ec8e1fb
